name: Deploy Web via SSM
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      AWS_PAGER: ""           # no pagers in CI logs
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS creds (temp tokens supported)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Resolve running instance IDs by tag
        id: ids
        run: |
          set -e
          IDS=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=cs1nca-dev-web" "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" --output text)
          echo "Found: $IDS"
          if [ -z "$IDS" ]; then
            echo "No running instances with Name=cs1nca-dev-web"; exit 1
          fi
          echo "IDS=$IDS" >> $GITHUB_OUTPUT
      
      - name: Build SSM parameters (install node_exporter)
        run: |
          # no comments inside JSON! build a clean commands array
          cat > params.json <<'EOF'
          {
            "commands": [
              "set -euxo pipefail",
              "VER=1.8.2",
              "cd /tmp",
              "curl -L -o ne.tar.gz https://github.com/prometheus/node_exporter/releases/download/v${VER}/node_exporter-${VER}.linux-amd64.tar.gz",
              "tar xf ne.tar.gz",
              "sudo mv node_exporter-${VER}.linux-amd64/node_exporter /usr/local/bin/",
              "sudo id nodeexp 2>/dev/null || sudo useradd -rs /bin/false nodeexp",
              "sudo bash -lc 'cat >/etc/systemd/system/node_exporter.service <<UNIT\n[Unit]\nDescription=Prometheus Node Exporter\nAfter=network.target\n\n[Service]\nUser=nodeexp\nExecStart=/usr/local/bin/node_exporter --web.listen-address=:9100\n\n[Install]\nWantedBy=multi-user.target\nUNIT'",
              "sudo systemctl daemon-reload",
              "sudo systemctl enable --now node_exporter",
              "curl -sI http://127.0.0.1:9100/metrics | head -n1 || true"
            ]
          }
          EOF
          echo "Params:"; cat params.json



      - name: Send SSM command (update index.html)
        id: send
        run: |
          CMD_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids ${{ steps.ids.outputs.IDS }} \
            --parameters file://params.json \
            --comment "Deploy simple page via GitHub Actions" \
            --query "Command.CommandId" --output text)
          echo "CommandId: $CMD_ID"
          echo "CMD_ID=$CMD_ID" >> $GITHUB_OUTPUT

      - name: Wait for SSM completion (per instance)
        run: |
          set -e
          for ID in ${{ steps.ids.outputs.IDS }}; do
            echo "Waiting on $ID ..."
            for i in $(seq 1 30); do
              STATUS=$(aws ssm get-command-invocation \
                --command-id "${{ steps.send.outputs.CMD_ID }}" \
                --instance-id "$ID" \
                --query 'Status' --output text 2>/dev/null || true)
              echo "$ID status: $STATUS"
              if [ "$STATUS" = "Success" ]; then break; fi
              if [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ] || [ "$STATUS" = "TimedOut" ]; then
                exit 1
              fi
              sleep 5
            done
          done
      - name: Dump SSM output on failure
        if: failure()
        run: |
          echo "CommandId: ${{ steps.send.outputs.CMD_ID }}"
          for ID in ${{ steps.ids.outputs.IDS }}; do
            echo "---- $ID ----"
            aws ssm get-command-invocation \
              --command-id "${{ steps.send.outputs.CMD_ID }}" \
              --instance-id "$ID" \
              --query '{Status:Status,Code:ResponseCode,StdErr:StandardErrorContent,StdOut:StandardOutputContent}' \
              --output json || true
          done
