name: Terraform CI
on:
  push:
    paths: [ "infrastructure/**" ]
  pull_request:
    paths: [ "infrastructure/**" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/envs/dev
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -backend=false -input=false
      - run: terraform fmt -check
      - run: terraform validate
